apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: score-api-serverless
  namespace: gamecloud
spec:
  hosts:
    - gamecloud.local
  scaleTargetRef:
    name: score-api
    service: score-service
    port: 80
  replicas:
    min: 0
    max: 5
  scaledownPeriod: 120
