name: memory-api
image:
  repository: 915993062361.dkr.ecr.eu-west-3.amazonaws.com/gamecloud/memory-api
  tag: 909134b0eb7bd05cbfefc07e1c2e50e010ca55bb
port: 3002
env:
  - name: REDIS_HOST
    value: redis-service
