name: puissance4-api
image:
  repository: 915993062361.dkr.ecr.eu-west-3.amazonaws.com/gamecloud/puissance4-api
  tag: 909134b0eb7bd05cbfefc07e1c2e50e010ca55bb
port: 5003
env:
  - name: REDIS_HOST
    value: redis-service
