name: auth-api
image:
  repository: 915993062361.dkr.ecr.eu-west-3.amazonaws.com/gamecloud/auth-api
  tag: 5f3fe364dd53b7a600f88a977e3a88e1e5bada52
port: 5001
env:
  - name: DB_HOST
    value: postgres-service
  - name: DB_NAME
    value: gamecloud
  - name: DB_USER
    value: postgres
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: gamecloud-secrets
        key: POSTGRES_PASSWORD
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: gamecloud-secrets
        key: JWT_SECRET
