name: memory-api
image:
  repository: 915993062361.dkr.ecr.eu-west-3.amazonaws.com/gamecloud/memory-api
  tag: 5f3fe364dd53b7a600f88a977e3a88e1e5bada52
port: 3002
healthCheckPath: /healthz
env:
  - name: REDIS_HOST
    value: redis-service
