apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: gamecloud-kibana
  namespace: monitoring
spec:
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: gamecloud-logs
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1Gi
